import turtle

turtle.bgcolor("black")
turtle.color("red")
turtle.begin_fill()
turtle.pensize(3)
turtle.speed(5)
turtle.left(50)
turtle.forward(133)
turtle.circle(50,200)
turtle.right(140)
turtle.circle(50,200)
turtle.forward(133)
turtle.end_fill()
turtle.hideturtle()
turtle.mainloop()
